# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionModel',
            new_name='Question',
        ),
    ]
