# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160211_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.IntegerField(default=50, primary_key=True, serialize=False),
        ),
    ]
